const sources = [
  { key: "bbc_world", name: "BBC World", url: "https://feeds.bbci.co.uk/news/world/rss.xml", enabledByDefault: true, continent: "Europe" },
  { key: "bbc_sci", name: "BBC Science", url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", enabledByDefault: true, continent: "Europe" },
  { key: "guardian_world", name: "The Guardian World", url: "https://www.theguardian.com/world/rss", enabledByDefault: true, continent: "Europe" },
  { key: "guardian_tech", name: "The Guardian Technology", url: "https://www.theguardian.com/uk/technology/rss", enabledByDefault: true, continent: "Europe" },
  { key: "france24_en", name: "France24 (EN)", url: "https://www.france24.com/en/rss", enabledByDefault: true, continent: "Europe" },
  { key: "france24_fr", name: "France24 (FR)", url: "https://www.france24.com/fr/rss", enabledByDefault: true, continent: "Europe" },
  { key: "aljazeera", name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", enabledByDefault: true, continent: "Asie" },
  { key: "times_of_india", name: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", enabledByDefault: true, continent: "Asie" },
  { key: "jakarta_post", name: "The Jakarta Post", url: "https://www.thejakartapost.com/rss", enabledByDefault: true, continent: "Asie" },
  { key: "nikkei_asia", name: "Nikkei Asia", url: "https://asia.nikkei.com/rss/feed/nar", enabledByDefault: true, continent: "Asie" },
  { key: "channel_news_asia", name: "CNA (Channel NewsAsia)", url: "https://www.channelnewsasia.com/rssfeeds/8395986", enabledByDefault: true, continent: "Asie" },
  { key: "straits_times", name: "The Straits Times", url: "https://www.straitstimes.com/rss", enabledByDefault: true, continent: "Asie" },
  { key: "bangkok_post", name: "Bangkok Post", url: "https://www.bangkokpost.com/rss/data/topstories.xml", enabledByDefault: true, continent: "Asie" },
  { key: "korea_times", name: "The Korea Times", url: "https://www.koreatimes.co.kr/www/rss/rss.xml", enabledByDefault: true, continent: "Asie" },
  { key: "malay_mail", name: "Malay Mail", url: "https://www.malaymail.com/rss/rss.xml", enabledByDefault: true, continent: "Asie" },
  { key: "haaretz", name: "Haaretz", url: "https://www.haaretz.com/srv/feed.xml", enabledByDefault: true, continent: "Asie" },
  { key: "yna", name: "Yonhap News", url: "https://en.yna.co.kr/rss/news.xml", enabledByDefault: true, continent: "Asie" },
  { key: "hindustan_times", name: "Hindustan Times", url: "https://www.hindustantimes.com/rss/topnews/rssfeed.xml", enabledByDefault: true, continent: "Asie" },
  { key: "dawn", name: "Dawn", url: "https://www.dawn.com/feeds/home", enabledByDefault: true, continent: "Asie" },
  { key: "npr", name: "NPR News", url: "https://www.npr.org/rss/rss.php?id=1001", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "nasa", name: "NASA Breaking News", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "lemonde", name: "Le Monde — À la une", url: "https://www.lemonde.fr/rss/une.xml", enabledByDefault: true, continent: "Europe" },
  { key: "dw", name: "DW — World", url: "https://rss.dw.com/rdf/rss-en-all", enabledByDefault: true, continent: "Europe" },
  { key: "cbc_world", name: "CBC — World", url: "https://www.cbc.ca/cmlink/rss-world", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "cnn_world", name: "CNN — World", url: "http://rss.cnn.com/rss/edition_world.rss", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "cnn_tech", name: "CNN — Technology", url: "http://rss.cnn.com/rss/edition_technology.rss", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "sky_world", name: "Sky News — World", url: "https://feeds.skynews.com/feeds/rss/world.xml", enabledByDefault: true, continent: "Europe" },
  { key: "sky_tech", name: "Sky News — Technology", url: "https://feeds.skynews.com/feeds/rss/technology.xml", enabledByDefault: true, continent: "Europe" },
  { key: "abc_au", name: "ABC News AU — Top Stories", url: "https://www.abc.net.au/news/feed/51120/rss.xml", enabledByDefault: true, continent: "Océanie" },
  { key: "rnz", name: "RNZ News", url: "https://www.rnz.co.nz/rss/news.xml", enabledByDefault: true, continent: "Océanie" },
  { key: "sbs_au", name: "SBS News (AU)", url: "https://www.sbs.com.au/news/rss/news", enabledByDefault: true, continent: "Océanie" },
  { key: "guardian_au", name: "The Guardian Australia", url: "https://www.theguardian.com/australia-news/rss", enabledByDefault: true, continent: "Océanie" },
  { key: "nz_herald", name: "NZ Herald", url: "https://www.nzherald.co.nz/rss/", enabledByDefault: true, continent: "Océanie" },
  { key: "nine_news_au", name: "9News Australia", url: "https://www.9news.com.au/rss", enabledByDefault: true, continent: "Océanie" },
  { key: "ap_top", name: "AP News — Top", url: "https://apnews.com/apf-topnews?format=rss", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "elespectador", name: "El Espectador", url: "https://www.elespectador.com/rss/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "eltiempo", name: "El Tiempo", url: "https://www.eltiempo.com/rss/colombia.xml", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "clarin", name: "Clarín", url: "https://www.clarin.com/rss/lo-ultimo/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "lanacion", name: "La Nación (AR)", url: "https://www.lanacion.com.ar/rss/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "folha", name: "Folha de S.Paulo", url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "oglobo", name: "O Globo", url: "https://oglobo.globo.com/rss.xml", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "emol", name: "Emol", url: "https://www.emol.com/rss/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "telesur", name: "teleSUR", url: "https://www.telesurenglish.net/rss/index.html", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "peru21", name: "Perú21", url: "https://peru21.pe/feed/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "larepublica_pe", name: "La República (PE)", url: "https://larepublica.pe/rss", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "elcomercio", name: "El Comercio (PE)", url: "https://elcomercio.pe/rss/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "la_tercera", name: "La Tercera", url: "https://www.latercera.com/feed/", enabledByDefault: true, continent: "Amérique du Sud" },
  { key: "reuters_world", name: "Reuters — World", url: "https://feeds.reuters.com/Reuters/worldNews", enabledByDefault: true, continent: "Europe" },
  { key: "reuters_tech", name: "Reuters — Tech", url: "https://feeds.reuters.com/reuters/technologyNews", enabledByDefault: true, continent: "Europe" },
  { key: "nytimes_world", name: "NYTimes — World", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "nytimes_tech", name: "NYTimes — Technology", url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "washpost_world", name: "Washington Post — World", url: "https://feeds.washingtonpost.com/rss/world", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "politico", name: "Politico — Top", url: "https://www.politico.com/rss/politicopicks.xml", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "un_news", name: "UN News", url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "who_news", name: "WHO News", url: "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "worldbank", name: "World Bank News", url: "https://www.worldbank.org/en/news/all.rss", enabledByDefault: true, continent: "Global" },
  { key: "imf", name: "IMF News", url: "https://www.imf.org/en/News/RSS", enabledByDefault: true, continent: "Global" },
  { key: "reliefweb", name: "ReliefWeb Updates", url: "https://reliefweb.int/updates/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "ifrc", name: "IFRC News", url: "https://www.ifrc.org/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "wfp", name: "WFP News", url: "https://www.wfp.org/news/reports?field_blog_topics_tid=All&format=RSS", enabledByDefault: true, continent: "Global" },
  { key: "unhcr", name: "UNHCR News", url: "https://www.unhcr.org/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "ilo", name: "ILO News", url: "https://www.ilo.org/global/about-the-ilo/newsroom/rss/lang--en/index.htm", enabledByDefault: true, continent: "Global" },
  { key: "undp", name: "UNDP News", url: "https://www.undp.org/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "oecd", name: "OECD News", url: "https://www.oecd.org/newsroom/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "unicef", name: "UNICEF News", url: "https://www.unicef.org/press-releases/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "care", name: "CARE International", url: "https://www.care-international.org/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "msf", name: "MSF (Doctors Without Borders)", url: "https://www.msf.org/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "amnesty", name: "Amnesty International", url: "https://www.amnesty.org/en/latest/news/rss.xml", enabledByDefault: true, continent: "Global" },
  { key: "econ", name: "The Economist — Latest", url: "https://www.economist.com/latest/rss.xml", enabledByDefault: true, continent: "Europe" },
  { key: "techcrunch", name: "TechCrunch", url: "https://techcrunch.com/feed/", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "ars", name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "mit_tech", name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "noaa", name: "NOAA News", url: "https://www.noaa.gov/feeds/news/rss.xml", enabledByDefault: true, continent: "Amérique du Nord" },
  { key: "afp", name: "AFP — Monde", url: "https://www.afp.com/fr/infos/rss", enabledByDefault: true, continent: "Global" },
  { key: "africanews", name: "Africanews", url: "https://www.africanews.com/feed/rss", enabledByDefault: true, continent: "Afrique" },
  { key: "allafrica", name: "AllAfrica", url: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", enabledByDefault: true, continent: "Afrique" },
  { key: "premium_times", name: "Premium Times", url: "https://www.premiumtimesng.com/feed", enabledByDefault: true, continent: "Afrique" },
  { key: "daily_nation_ke", name: "Daily Nation (KE)", url: "https://nation.africa/kenya/news/rss", enabledByDefault: true, continent: "Afrique" },
  { key: "standard_ke", name: "The Standard (KE)", url: "https://www.standardmedia.co.ke/rss/kenya.php", enabledByDefault: true, continent: "Afrique" },
  { key: "news24", name: "News24", url: "https://www.news24.com/news24/rss", enabledByDefault: true, continent: "Afrique" },
  { key: "eyewitness", name: "Eyewitness News", url: "https://www.ewn.co.za/rss/news", enabledByDefault: true, continent: "Afrique" },
  { key: "sabc", name: "SABC News", url: "https://www.sabcnews.com/sabcnews/feed/", enabledByDefault: true, continent: "Afrique" },
  { key: "mg", name: "Mail & Guardian", url: "https://mg.co.za/feed/", enabledByDefault: true, continent: "Afrique" },
  { key: "enca", name: "eNCA", url: "https://www.enca.com/rss", enabledByDefault: true, continent: "Afrique" },
  { key: "ghana_web", name: "GhanaWeb", url: "https://www.ghanaweb.com/GhanaHomePage/NewsArchive/rss.php", enabledByDefault: true, continent: "Afrique" },
  { key: "myjoyonline", name: "MyJoyOnline", url: "https://www.myjoyonline.com/feed/", enabledByDefault: true, continent: "Afrique" },
  { key: "monitor_ug", name: "Daily Monitor (UG)", url: "https://www.monitor.co.ug/uganda/news/-/691064/691072/-/view/asFeed/-/14azrmnz/-/index.xml", enabledByDefault: true, continent: "Afrique" },
  { key: "newtimes_rw", name: "The New Times (RW)", url: "https://www.newtimes.co.rw/section/rss/news", enabledByDefault: true, continent: "Afrique" },
  { key: "morocco_world_news", name: "Morocco World News", url: "https://www.moroccoworldnews.com/feed", enabledByDefault: true, continent: "Afrique" },
  { key: "al_ahran", name: "Al-Ahram (EG)", url: "https://english.ahram.org.eg/rss.aspx", enabledByDefault: true, continent: "Afrique" }
];

export default sources;
